[package]
name = "rs_shader"
version = "0.1.0"
authors = ["fireyang <shenhuan007@gmail.com>"]


[dependencies]
glium = "0.18.1"
image = "0.17.0"
imgui = { version = "0.0.18-pre", path = "imgui-rs" }
imgui-glium-renderer = { version = "0.0.18-pre", path = "./imgui-rs/imgui-glium-renderer" }
